#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\Controller\Login::check
mainpage:
    path: /
    controller: App\Controller\MainPage::base

