<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3CWRd4Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3CWRd4Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3CWRd4Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3CWRd4Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3CWRd4Q\App_KernelDevDebugContainer([
    'container.build_hash' => '3CWRd4Q',
    'container.build_id' => '5e5bea4c',
    'container.build_time' => 1592660116,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3CWRd4Q');
