<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZt1u1f1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZt1u1f1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZt1u1f1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZt1u1f1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZt1u1f1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zt1u1f1',
    'container.build_id' => '3fd13dfe',
    'container.build_time' => 1591530348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZt1u1f1');
